Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1051b4e50>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1054d1870>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1054d1870>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1054d1900>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1054d1900>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1054d1900>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1054d1900>>
      paths = ('./mysite.local/private/backups/20250808_010002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250808_010002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1054d1900>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1054d1900>>
      paths = ('./mysite.local/private/backups/20250808_010002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250808_010002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1050953f0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250808_010002-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104ea2290>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1054d1900>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105f517e0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '88ca88fd61e03d92c2699b07efbbeace857ea5ec6c4e3626c68d4f5b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '88ca88fd61e03d92c2699b07efbbeace857ea5ec6c4e3626c68d4f5b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103bd4e50>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103dc2e60>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103dc2e60>
      odb = <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>>
      paths = ('./mysite.local/private/backups/20250811_000002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_000002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>>
      paths = ('./mysite.local/private/backups/20250811_000002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_000002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103abd3f0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250811_000002-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1037a2290>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x103dc2ef0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10426d7e0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f28e76abfb6e2db40a9b8d7b0a60bfca29aa768d7ee48f2a1546e1ae'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f28e76abfb6e2db40a9b8d7b0a60bfca29aa768d7ee48f2a1546e1ae'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1061d4e50>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1063c30d0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1063c30d0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1063c3160>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1063c3160>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1063c3160>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1063c3160>>
      paths = ('./mysite.local/private/backups/20250811_060001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_060001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1063c3160>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1063c3160>>
      paths = ('./mysite.local/private/backups/20250811_060001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_060001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1060bd3f0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250811_060001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105ec6290>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1063c3160>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10696d7e0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ff5444931607cd4f0021d0bfe87c79d90e20567ead2d64bed15a8823'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ff5444931607cd4f0021d0bfe87c79d90e20567ead2d64bed15a8823'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x10412ce50>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104317220>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104317220>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1043172b0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1043172b0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1043172b0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1043172b0>>
      paths = ('./mysite.local/private/backups/20250811_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1043172b0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1043172b0>>
      paths = ('./mysite.local/private/backups/20250811_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1040153f0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250811_120001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103e1e290>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1043172b0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1047c97e0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4d9f1d6f8f46337451d9e961e3351b4a1284c9a1f770c79636f93fef'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4d9f1d6f8f46337451d9e961e3351b4a1284c9a1f770c79636f93fef'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105304e50>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105501690>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105501690>
      odb = <frappe.utils.backups.BackupGenerator object at 0x105501720>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x105501720>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x105501720>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105501720>>
      paths = ('./mysite.local/private/backups/20250811_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x105501720>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105501720>>
      paths = ('./mysite.local/private/backups/20250811_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250811_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1051e53f0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250811_180001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104ff2290>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x105501720>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1059997e0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'be0f9bd20138f791b392daffe55a9afac949cd37772d59675780bffa'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'be0f9bd20138f791b392daffe55a9afac949cd37772d59675780bffa'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1087c75b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x108c08130>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x108c08130>
      odb = <frappe.utils.backups.BackupGenerator object at 0x108c081c0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x108c081c0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x108c081c0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108c081c0>>
      paths = ('./mysite.local/private/backups/20250815_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250815_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x108c081c0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108c081c0>>
      paths = ('./mysite.local/private/backups/20250815_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250815_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10866bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250815_120001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1084b4a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x108c081c0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1059e0160>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'c55aed4ca71efd3825bab385f4b29be27b0596fe277cfe8aa50d48c4'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'c55aed4ca71efd3825bab385f4b29be27b0596fe277cfe8aa50d48c4'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1057eb5b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1059cfa90>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1059cfa90>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>>
      paths = ('./mysite.local/private/backups/20250815_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250815_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>>
      paths = ('./mysite.local/private/backups/20250815_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250815_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10568bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250815_180001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105368a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1059cfb20>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x103638160>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ee06fb26c8899599e4721cfdcc21c4f40610bf3638d76668eb8275c1'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ee06fb26c8899599e4721cfdcc21c4f40610bf3638d76668eb8275c1'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1035c75b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1037abc40>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1037abc40>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>>
      paths = ('./mysite.local/private/backups/20250818_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250818_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>>
      paths = ('./mysite.local/private/backups/20250818_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250818_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103467b50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250818_180001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1032b8a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1037abcd0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1013ac160>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6f193a20c71a0f7b45b33fca6713bcff14a6ad85b6fedb49db3145d1'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6f193a20c71a0f7b45b33fca6713bcff14a6ad85b6fedb49db3145d1'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103beb5b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103dcbbe0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103dcbbe0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>>
      paths = ('./mysite.local/private/backups/20250821_180003-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250821_180003-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>>
      paths = ('./mysite.local/private/backups/20250821_180003-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250821_180003-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103a8bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250821_180003-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1038dca60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x103dcbc70>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10193c160>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'a79395189740cacfad24d3bca93066d1fb292d6e37e808b0fd27b9bc'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'a79395189740cacfad24d3bca93066d1fb292d6e37e808b0fd27b9bc'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1041eb5b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1044042e0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1044042e0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104404370>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104404370>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104404370>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104404370>>
      paths = ('./mysite.local/private/backups/20250822_000002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250822_000002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104404370>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104404370>>
      paths = ('./mysite.local/private/backups/20250822_000002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250822_000002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10408fb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250822_000002-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103ddca60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x104404370>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1046300d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9c6ed8c88d27a6adb0d575145c19c7901a90aede3bff1bd78f5ca276'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9c6ed8c88d27a6adb0d575145c19c7901a90aede3bff1bd78f5ca276'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1104eb5b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x110708160>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x110708160>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1107081f0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1107081f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1107081f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1107081f0>>
      paths = ('./mysite.local/private/backups/20250822_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250822_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1107081f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1107081f0>>
      paths = ('./mysite.local/private/backups/20250822_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250822_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x11038bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250822_120001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1101dca60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1107081f0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1109300d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '461d00baf0edf91ede034fc130a61770d1537a2dc0e04b3754af5afa'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '461d00baf0edf91ede034fc130a61770d1537a2dc0e04b3754af5afa'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1061435b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106327fd0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106327fd0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1063640a0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1063640a0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1063640a0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1063640a0>>
      paths = ('./mysite.local/private/backups/20250824_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250824_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1063640a0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1063640a0>>
      paths = ('./mysite.local/private/backups/20250824_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250824_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x105fe3b50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250824_120001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105e30a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1063640a0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1065880d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '129f7dd6e66a3dc702f3015409bda3599716574495008a5a9b7fd2dd'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '129f7dd6e66a3dc702f3015409bda3599716574495008a5a9b7fd2dd'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107dc75b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1180042b0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1180042b0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x118004340>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x118004340>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x118004340>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x118004340>>
      paths = ('./mysite.local/private/backups/20250825_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250825_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x118004340>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x118004340>>
      paths = ('./mysite.local/private/backups/20250825_120001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250825_120001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x107c6bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250825_120001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107ab8a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x118004340>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x11822c0d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd12437cf84b84165cabd34b9c7a00423148fd8650706a015850f22b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd12437cf84b84165cabd34b9c7a00423148fd8650706a015850f22b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103deb5b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1040081f0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1040081f0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104008280>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104008280>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104008280>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104008280>>
      paths = ('./mysite.local/private/backups/20250826_060002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250826_060002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104008280>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104008280>>
      paths = ('./mysite.local/private/backups/20250826_060002-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250826_060002-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103c8fb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250826_060002-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103adca60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x104008280>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10432c0d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6c17215e9ee1c01631ffa4e4694e93cbdbc2fcf5802b0c08b8e5e12e'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6c17215e9ee1c01631ffa4e4694e93cbdbc2fcf5802b0c08b8e5e12e'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107e275b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1080383d0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1080383d0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x108038460>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x108038460>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x108038460>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108038460>>
      paths = ('./mysite.local/private/backups/20250831_120003-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250831_120003-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x108038460>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108038460>>
      paths = ('./mysite.local/private/backups/20250831_120003-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250831_120003-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x107ccbb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250831_120003-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107b18a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x108038460>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1082680d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'e2db29ba3c5336004d869b4277c7e9532a2c2c686066f9faadbb042d'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'e2db29ba3c5336004d869b4277c7e9532a2c2c686066f9faadbb042d'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1068c75b0>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106bfc400>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106bfc400>
      odb = <frappe.utils.backups.BackupGenerator object at 0x106bfc490>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x106bfc490>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x106bfc490>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106bfc490>>
      paths = ('./mysite.local/private/backups/20250831_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250831_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x106bfc490>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106bfc490>>
      paths = ('./mysite.local/private/backups/20250831_180001-mysite_local-database.sql.gz',)
      path = './mysite.local/private/backups/20250831_180001-mysite_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10676bb50>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.76.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.76.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./mysite.local/private/backups/20250831_180001-mysite_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1065b4a60>
      bin = None
      args = ['--user=_0b0250d68beed0d7', '--host=127.0.0.1', '--port=3306', '--password=new_password', '--single-transaction', '--quick', '--lock-tables=false', '_0b0250d68beed0d7']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x106bfc490>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x106e300d0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '47c871d5b0af32d34b3b76a9143199aee0b7af79230fee80b70cd8be'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '47c871d5b0af32d34b3b76a9143199aee0b7af79230fee80b70cd8be'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Traceback (most recent call last):
  File "/Users/simo/Dev/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'swiss_accounting_integration'
Backup failed for Site mysite.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 840, in backup
    frappe.init(site=site)
      context = {'sites': ['mysite.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107e41b40>
      exit_code = 0
      rollback_callback = None
      site = 'mysite.local'
  File "apps/frappe/frappe/__init__.py", line 258, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
      site = 'mysite.local'
      sites_path = '.'
      new_site = False
      force = False
  File "apps/frappe/frappe/__init__.py", line 1670, in setup_module_map
    for module in get_module_list(app):
      include_all_apps = True
      apps = ['frappe', 'eb_invoice_templates', 'eb_vies', 'email_delivery_service', 'erpnext', 'plato_excise', 'swiss_accounting_integration', 'truth_source', 'vies']
      app = 'swiss_accounting_integration'
      module = 'plato_excise'
  File "apps/frappe/frappe/__init__.py", line 1518, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
      app_name = 'swiss_accounting_integration'
  File "apps/frappe/frappe/__init__.py", line 1483, in get_app_path
    return get_pymodule_path(app_name, *joins)
      app_name = 'swiss_accounting_integration'
      joins = ('modules.txt',)
  File "apps/frappe/frappe/__init__.py", line 1513, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
      modulename = 'swiss_accounting_integration'
      joins = ['modules.txt']
      abspath = <function abspath at 0x104e0b010>
      dirname = <function dirname at 0x104e0ac20>
      join = <function join at 0x104e0a950>
  File "apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
      modulename = 'swiss_accounting_integration'
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      name = 'swiss_accounting_integration'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      name = 'swiss_accounting_integration'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      name = 'swiss_accounting_integration'
      import_ = <function _gcd_import at 0x104cfb400>
      module = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 331, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable
        
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
      name = 'swiss_accounting_integration'
      import_ = <function _gcd_import at 0x104cfb400>
      path = None
      parent = ''
      spec = None
builtins.ModuleNotFoundError: No module named 'swiss_accounting_integration'
Backup failed for Site excise.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['excise.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1042a9bd0>
      exit_code = 0
      rollback_callback = None
      site = 'excise.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1044affa0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1044affa0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1044affd0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1044affd0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1044affd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1044affd0>>
      paths = ('./excise.local/private/backups/20250908_120001-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250908_120001-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1044affd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1044affd0>>
      paths = ('./excise.local/private/backups/20250908_120001-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250908_120001-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1041420e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.80.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.80.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./excise.local/private/backups/20250908_120001-excise_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103f8ef80>
      bin = None
      args = ['--user=excise_db', '--host=127.0.0.1', '--port=3306', '--password=excice_pass', '--single-transaction', '--quick', '--lock-tables=false', 'excise_db']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1044affd0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x101792a70>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ea634518885e313ec16c8ff66231ef029692a2e5e4517f8ad6c1576'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ea634518885e313ec16c8ff66231ef029692a2e5e4517f8ad6c1576'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site excise.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['excise.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105265bd0>
      exit_code = 0
      rollback_callback = None
      site = 'excise.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10546ff40>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10546ff40>
      odb = <frappe.utils.backups.BackupGenerator object at 0x10546ff70>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x10546ff70>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x10546ff70>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10546ff70>>
      paths = ('./excise.local/private/backups/20250908_180501-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250908_180501-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x10546ff70>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10546ff70>>
      paths = ('./excise.local/private/backups/20250908_180501-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250908_180501-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1050fe0e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.80.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.80.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./excise.local/private/backups/20250908_180501-excise_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104f4af80>
      bin = None
      args = ['--user=excise_db', '--host=127.0.0.1', '--port=3306', '--password=excice_pass', '--single-transaction', '--quick', '--lock-tables=false', 'excise_db']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x10546ff70>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1032aea70>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ba3f229fb2ecf917a89ea20077a50f886dda580362e6ef4cc551bf7'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ba3f229fb2ecf917a89ea20077a50f886dda580362e6ef4cc551bf7'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site excise.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['excise.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105fedbd0>
      exit_code = 0
      rollback_callback = None
      site = 'excise.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1062bfdc0>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1062bfdc0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>>
      paths = ('./excise.local/private/backups/20250914_120851-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250914_120851-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>>
      paths = ('./excise.local/private/backups/20250914_120851-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250914_120851-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x105e860e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.80.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.80.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./excise.local/private/backups/20250914_120851-excise_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105cd2f80>
      bin = None
      args = ['--user=excise_db', '--host=127.0.0.1', '--port=3306', '--password=excice_pass', '--single-transaction', '--quick', '--lock-tables=false', 'excise_db']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x1062bfe50>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x103dc6a70>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9b8b624cc26b92451874573e1b4727f2fbb86ad14997261202c3e767'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9b8b624cc26b92451874573e1b4727f2fbb86ad14997261202c3e767'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site excise.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['excise.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x108bedbd0>
      exit_code = 0
      rollback_callback = None
      site = 'excise.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x108dc3940>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x108dc3940>
      odb = <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>>
      paths = ('./excise.local/private/backups/20250915_120001-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250915_120001-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>>
      paths = ('./excise.local/private/backups/20250915_120001-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250915_120001-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x108a920e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.80.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.80.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./excise.local/private/backups/20250915_120001-excise_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1086f6f80>
      bin = None
      args = ['--user=excise_db', '--host=127.0.0.1', '--port=3306', '--password=excice_pass', '--single-transaction', '--quick', '--lock-tables=false', 'excise_db']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x108dc39d0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105f16a70>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '08e2da17d80b3f2372fe0f6c8c5d5dfb6726e34a40263747c24cad60'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '08e2da17d80b3f2372fe0f6c8c5d5dfb6726e34a40263747c24cad60'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site excise.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['excise.local'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x104bedbd0>
      exit_code = 0
      rollback_callback = None
      site = 'excise.local'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104dbff70>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104dbff70>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>>
      paths = ('./excise.local/private/backups/20250918_060002-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250918_060002-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>>
      paths = ('./excise.local/private/backups/20250918_060002-excise_local-database.sql.gz',)
      path = './excise.local/private/backups/20250918_060002-excise_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x104a860e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.80.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.80.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./excise.local/private/backups/20250918_060002-excise_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1046f6f80>
      bin = None
      args = ['--user=excise_db', '--host=127.0.0.1', '--port=3306', '--password=excice_pass', '--single-transaction', '--quick', '--lock-tables=false', 'excise_db']
      bin_name = 'mariadb-dump'
      self = <frappe.utils.backups.BackupGenerator object at 0x104dbffd0>
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x102016a70>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'a2a92d87c71b3403a081cc4891a97c6c2650cec2ff26401280072396'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'a2a92d87c71b3403a081cc4891a97c6c2650cec2ff26401280072396'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
